### ISSUE TITLE
Missing LocalStrings for javax.servlet in jakarta-platform 8.0.0

### ISSUE THREAD

**Issue by kalgon** [eclipse-ee4j/jakartaee-platform#172]
Some classes from `javax.servlet` which are bundled in jakarta-platform are using `LocalStrings.properties` resource bundles but those are not present in the maven central distribution.

Classes which are using `LocalStrings.properties` (from `javax.servlet` or `javax.servlet.http`) are: `GenericFilter`, `GenericServlet`, `ServletOutputStream`, `Cookie`, `HttpServlet` and `HttpUtils`.

Strangely, the jakarta-platform:jakartaee.jakartaee-api:8.0.0 (sources) contains all those `LocalStrings.properties` but the jar does not.

**Comment by kalgon** [comment]
Reproducer:

create a maven project which has a dependency to jakarta.platform:jakarta.jakartaee-api:8.0.0.

The following code
```java
new javax.servlet.http.Cookie("foo", "bar");
```
will throw an exception:
```
Caused by: java.util.MissingResourceException: Can't find bundle for base name javax.servlet.http.LocalStrings, locale en_US
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
	at javax.servlet.http.Cookie.<clinit>(Cookie.java:65)
```
Replace jakarta.platform:jakarta.jakartaee-api:8.0.0 with jakarta.servlet:jakarta.servlet-api:4.0.3 (which contains the bundles) and the code will run fine.
